In [1]:
# Importing Modules
import torch
import pandas as pd
import numpy as np
import itertools
from src.dataloader import loadData
from src.model import SimpleGCN, SimpleGAT, SimpleGIN, SimpleGraphSAGE
from src.train_test import TrainGNN, TestGNN
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
######################## DATA-1 ##################################
# Loading ESOL data
esol_train_data = pd.read_csv("data/train/ESOL.csv")
esol_test_data = pd.read_csv("data/test/ESOL.csv")

######################## DATA-2 ##################################
# Loading FreeSolv data
freeSolv_train_data = pd.read_csv("data/train/FreeSolv.csv")
freeSolv_test_data = pd.read_csv("data/test/FreeSolv.csv")

######################## DATA-3 ##################################
# Loading Lipophilicity data
lipophilicity_train_data = pd.read_csv("data/train/Lipophilicity.csv")
lipophilicity_test_data = pd.read_csv("data/test/Lipophilicity.csv")

In [3]:
# Models
model_dict = {
        "SimpleGCN":SimpleGCN, 
		"SimpleGAT":SimpleGAT, 
		"SimpleGIN":SimpleGIN,
		"SimpleGraphSAGE":SimpleGraphSAGE
}

# Models Hyperparameters
model_hyperparams_dict = {
        "SimpleGCN":[0.01, 64, 8],
        "SimpleGAT":[0.005, 128, 32],
        "SimpleGIN":[0.001, 64, 4],
        "SimpleGraphSAGE":[0.005, 128, 4]
}

# Function to run analysis
def RunGNN(model, train_data, test_data, dataName, modelName, params, f):
    
	# Training data and target labels
	smiles_X_train = train_data["smiles"]
	X_train = smiles_X_train.to_numpy()
	y_train = train_data["target"]
	y_train = y_train.to_numpy()

    # Testing data and target labels
	smiles_X_test = test_data["smiles"]
	X_test = smiles_X_test.to_numpy()
	y_test = test_data["target"]
	y_test = y_test.to_numpy()

    # Params
	lr, h_dim, b_size = params

	# Loading dataset
	train_loader = loadData(X_train, y_train, batch_size=b_size, f_in=f)
	test_loader = loadData(X_test, y_test, batch_size=b_size, f_in=f)

	# Model
	model = model_dict[modelName](num_features=f, hidden_dim=h_dim, num_classes=1)

	# Model training
	model = TrainGNN(model, train_loader, epochs=100, learning_rate=lr)

	# Model testing
	y_test, y_pred = TestGNN(model, test_loader)

	# Calculate MAE
	mae = mean_absolute_error(y_test, y_pred)

	# Calculate RMSE
	rmse = root_mean_squared_error(y_test, y_pred)
    
    # Calculate pearson r and p_val
	r, p_val = pearsonr(y_test, y_pred)
    
	# Return results
	return pd.DataFrame({"Data":[dataName], "Model":[modelName],"n_Features":f,
			"MAE":round(mae, 2), "RMSE":[round(rmse, 2)], 
			"r":[round(r, 2)], "p-val":[round(p_val, 3)]})

# Feature Ablation

In [4]:
# Data dict
datasets = {
    "ESOL":{"train":esol_train_data, "test":esol_test_data},
    "FreeSolv":{"train":freeSolv_train_data, "test":freeSolv_test_data},
    "Lipophilicity":{"train":lipophilicity_train_data, "test":lipophilicity_test_data}
}

In [5]:
# List to store results
temp_out = []

# Loop for models
for modelName, model in model_dict.items():
    # Loop for dataset
    for dataName, data in datasets.items():
        # Loop for number of features
        for f in [2, 4, 6, 8]:
            # Run Analysis for model, dataset and number of features
            temp_out.append(RunGNN(model, data["train"], data["test"], dataName, modelName, model_hyperparams_dict[modelName], f))

# Final output
GNN_out = pd.concat(temp_out, ignore_index=True)
GNN_out.to_csv("results/Output_GNN_Feature_Ablation_Analysis.csv")
GNN_out

/tmp/ipykernel_2385829/2184828238.py:55: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  r, p_val = pearsonr(y_test, y_pred)

             Data            Model  n_Features   MAE  RMSE     r  p-val
0            ESOL        SimpleGCN           2  1.67  2.11  0.24    0.0
1            ESOL        SimpleGCN           4  1.45  1.87  0.52    0.0
2            ESOL        SimpleGCN           6  0.99  1.30  0.80    0.0
3            ESOL        SimpleGCN           8  1.02  1.31  0.80    0.0
4        FreeSolv        SimpleGCN           2  2.45  3.47  0.55    0.0
5        FreeSolv        SimpleGCN           4  2.16  2.96  0.70    0.0
6        FreeSolv        SimpleGCN           6  2.56  3.30  0.67    0.0
7        FreeSolv        SimpleGCN           8  2.39  2.98  0.74    0.0
8   Lipophilicity        SimpleGCN           2  0.98  1.22   NaN    NaN
9   Lipophilicity        SimpleGCN           4  0.94  1.18  0.27    0.0
10  Lipophilicity        SimpleGCN           6  0.92  1.16  0.34    0.0
11  Lipophilicity        SimpleGCN           8  0.92  1.14  0.36    0.0
12           ESOL        SimpleGAT           2  1.75  2.06  0.48    0.0
13           ESOL        SimpleGAT           4  1.85  2.16  0.45    0.0
14           ESOL        SimpleGAT           6  1.08  1.36  0.80    0.0
15           ESOL        SimpleGAT           8  1.23  1.50  0.80    0.0
16       FreeSolv        SimpleGAT           2  2.27  3.25  0.62    0.0
17       FreeSolv        SimpleGAT           4  2.39  3.34  0.61    0.0
18       FreeSolv        SimpleGAT           6  2.21  3.14  0.77    0.0
19       FreeSolv        SimpleGAT           8  2.79  4.01  0.51    0.0
20  Lipophilicity        SimpleGAT           2  1.01  1.33  0.30    0.0
21  Lipophilicity        SimpleGAT           4  0.93  1.15  0.34    0.0
22  Lipophilicity        SimpleGAT           6  0.87  1.11  0.50    0.0
23  Lipophilicity        SimpleGAT           8  0.87  1.13  0.55    0.0
24           ESOL        SimpleGIN           2  1.51  1.92  0.57    0.0
25           ESOL        SimpleGIN           4  1.47  1.78  0.66    0.0
26           ESOL        SimpleGIN           6  1.13  1.43  0.77    0.0
27           ESOL        SimpleGIN           8  1.03  1.34  0.79    0.0
28       FreeSolv        SimpleGIN           2  2.62  3.48  0.53    0.0
29       FreeSolv        SimpleGIN           4  2.25  3.06  0.67    0.0
30       FreeSolv        SimpleGIN           6  2.50  3.15  0.71    0.0
31       FreeSolv        SimpleGIN           8  2.32  3.23  0.68    0.0
32  Lipophilicity        SimpleGIN           2  0.94  1.17  0.29    0.0
33  Lipophilicity        SimpleGIN           4  0.89  1.12  0.42    0.0
34  Lipophilicity        SimpleGIN           6  0.89  1.10  0.43    0.0
35  Lipophilicity        SimpleGIN           8  0.88  1.09  0.46    0.0
36           ESOL  SimpleGraphSAGE           2  1.51  1.92  0.48    0.0
37           ESOL  SimpleGraphSAGE           4  1.59  1.93  0.51    0.0
38           ESOL  SimpleGraphSAGE           6  1.11  1.38  0.82    0.0
39           ESOL  SimpleGraphSAGE           8  1.08  1.42  0.79    0.0
40       FreeSolv  SimpleGraphSAGE           2  2.37  3.27  0.60    0.0
41       FreeSolv  SimpleGraphSAGE           4  1.96  2.78  0.75    0.0
42       FreeSolv  SimpleGraphSAGE           6  1.61  2.13  0.86    0.0
43       FreeSolv  SimpleGraphSAGE           8  1.47  1.87  0.89    0.0
44  Lipophilicity  SimpleGraphSAGE           2  0.94  1.17  0.30    0.0
45  Lipophilicity  SimpleGraphSAGE           4  0.90  1.13  0.40    0.0
46  Lipophilicity  SimpleGraphSAGE           6  0.95  1.15  0.48    0.0
47  Lipophilicity  SimpleGraphSAGE           8  0.91  1.11  0.48    0.0

In [6]:
# Function to plot barplot showing result
def plot_bar(data, target):
    sns.set_theme(style="ticks", context="paper")
    g = sns.catplot(data=data, kind="point", x="n_Features", y=target, hue="Model",
                    col="Data", col_wrap=3, sharey=False, height=4, width=0.8,
                    aspect=0.8, dodge=False, legend=True)
    g.set_axis_labels("Number of Features", f"{target}")
    g.set_titles("{col_name}")
    for ax in g.axes.flat:
        ax.tick_params(axis="x", rotation=40)
        ax.grid()
    plt.savefig(f"results/GNN_Analysis_Feature_Ablation_Plot.png", dpi=300)
    plt.close()

In [7]:
# Plotting barplot for RMSE
plot_bar(GNN_out, "RMSE")

# Feature Ablation: Validation

In [8]:
# Data dict
datasets = {
    "Lipophilicity_500":{"train":lipophilicity_train_data.sample(500), "test":lipophilicity_test_data},
    "Lipophilicity_1500":{"train":lipophilicity_train_data.sample(1500), "test":lipophilicity_test_data},
    "Lipophilicity_3000":{"train":lipophilicity_train_data.sample(3000), "test":lipophilicity_test_data}
}

In [9]:
# List to store results
temp_out = []

# Loop for models
for modelName, model in model_dict.items():
    # Loop for dataset
    for dataName, data in datasets.items():
        # Loop for number of features
        for f in [2, 4, 6, 8]:
            # Run Analysis for model, dataset and number of features
            temp_out.append(RunGNN(model, data["train"], data["test"], dataName, modelName, model_hyperparams_dict[modelName], f))

# Final output
GNN_out = pd.concat(temp_out, ignore_index=True)
GNN_out.to_csv("results/Output_Validation_GNN_Feature_Ablation_Analysis.csv")
GNN_out

                  Data            Model  n_Features   MAE  RMSE     r  p-val
0    Lipophilicity_500        SimpleGCN           2  0.97  1.21  0.10  0.003
1    Lipophilicity_500        SimpleGCN           4  0.97  1.25  0.14  0.000
2    Lipophilicity_500        SimpleGCN           6  0.94  1.22  0.28  0.000
3    Lipophilicity_500        SimpleGCN           8  0.95  1.17  0.27  0.000
4   Lipophilicity_1500        SimpleGCN           2  0.96  1.19  0.22  0.000
5   Lipophilicity_1500        SimpleGCN           4  0.94  1.18  0.30  0.000
6   Lipophilicity_1500        SimpleGCN           6  0.93  1.15  0.33  0.000
7   Lipophilicity_1500        SimpleGCN           8  0.92  1.15  0.34  0.000
8   Lipophilicity_3000        SimpleGCN           2  0.97  1.20  0.16  0.000
9   Lipophilicity_3000        SimpleGCN           4  0.94  1.17  0.29  0.000
10  Lipophilicity_3000        SimpleGCN           6  0.93  1.19  0.36  0.000
11  Lipophilicity_3000        SimpleGCN           8  0.88  1.10  0.44  0.000
12   Lipophilicity_500        SimpleGAT           2  0.98  1.25  0.19  0.000
13   Lipophilicity_500        SimpleGAT           4  0.97  1.25  0.21  0.000
14   Lipophilicity_500        SimpleGAT           6  0.94  1.17  0.31  0.000
15   Lipophilicity_500        SimpleGAT           8  0.92  1.20  0.31  0.000
16  Lipophilicity_1500        SimpleGAT           2  0.94  1.19  0.29  0.000
17  Lipophilicity_1500        SimpleGAT           4  0.95  1.21  0.30  0.000
18  Lipophilicity_1500        SimpleGAT           6  0.89  1.12  0.45  0.000
19  Lipophilicity_1500        SimpleGAT           8  0.86  1.09  0.51  0.000
20  Lipophilicity_3000        SimpleGAT           2  0.99  1.29  0.29  0.000
21  Lipophilicity_3000        SimpleGAT           4  0.94  1.20  0.32  0.000
22  Lipophilicity_3000        SimpleGAT           6  0.89  1.14  0.43  0.000
23  Lipophilicity_3000        SimpleGAT           8  0.86  1.05  0.58  0.000
24   Lipophilicity_500        SimpleGIN           2  0.96  1.18  0.28  0.000
25   Lipophilicity_500        SimpleGIN           4  0.93  1.19  0.33  0.000
26   Lipophilicity_500        SimpleGIN           6  0.93  1.20  0.34  0.000
27   Lipophilicity_500        SimpleGIN           8  0.91  1.15  0.34  0.000
28  Lipophilicity_1500        SimpleGIN           2  0.94  1.19  0.28  0.000
29  Lipophilicity_1500        SimpleGIN           4  0.91  1.13  0.40  0.000
30  Lipophilicity_1500        SimpleGIN           6  0.92  1.19  0.40  0.000
31  Lipophilicity_1500        SimpleGIN           8  0.90  1.12  0.39  0.000
32  Lipophilicity_3000        SimpleGIN           2  0.94  1.18  0.29  0.000
33  Lipophilicity_3000        SimpleGIN           4  0.89  1.13  0.43  0.000
34  Lipophilicity_3000        SimpleGIN           6  0.88  1.09  0.45  0.000
35  Lipophilicity_3000        SimpleGIN           8  0.88  1.11  0.46  0.000
36   Lipophilicity_500  SimpleGraphSAGE           2  0.95  1.19  0.22  0.000
37   Lipophilicity_500  SimpleGraphSAGE           4  0.93  1.16  0.31  0.000
38   Lipophilicity_500  SimpleGraphSAGE           6  0.90  1.13  0.39  0.000
39   Lipophilicity_500  SimpleGraphSAGE           8  0.90  1.14  0.37  0.000
40  Lipophilicity_1500  SimpleGraphSAGE           2  0.95  1.18  0.27  0.000
41  Lipophilicity_1500  SimpleGraphSAGE           4  0.92  1.14  0.35  0.000
42  Lipophilicity_1500  SimpleGraphSAGE           6  0.90  1.09  0.48  0.000
43  Lipophilicity_1500  SimpleGraphSAGE           8  0.88  1.13  0.45  0.000
44  Lipophilicity_3000  SimpleGraphSAGE           2  0.93  1.16  0.32  0.000
45  Lipophilicity_3000  SimpleGraphSAGE           4  0.91  1.12  0.39  0.000
46  Lipophilicity_3000  SimpleGraphSAGE           6  0.89  1.09  0.51  0.000
47  Lipophilicity_3000  SimpleGraphSAGE           8  0.85  1.07  0.48  0.000

In [10]:
# Function to plot barplot showing result
def plot_bar(data, target):
    sns.set_theme(style="ticks", context="paper")
    g = sns.catplot(data=data, kind="point", x="n_Features", y=target, hue="Model",
                    col="Data", col_wrap=3, sharey=False, height=4, width=0.8,
                    aspect=0.8, dodge=False, legend=True)
    g.set_axis_labels("Number of Features", f"{target}")
    g.set_titles("{col_name}")
    for ax in g.axes.flat:
        ax.tick_params(axis="x", rotation=40)
        ax.grid()
    plt.savefig(f"results/GNN_Analysis_Feature_Ablation_Validation_Plot.png", dpi=300)
    plt.close()

In [11]:
# Plotting barplot for RMSE
plot_bar(GNN_out, "RMSE")